const r = require('express').Router();
const c = require('../controllers/admin.controller');
const { protect, adminOnly } = require('../middleware/auth.middleware');
r.use(protect, adminOnly);
r.get('/stats', c.getStats);
r.get('/registrations', c.getRegistrations);
r.put('/registrations/:id', c.updateRegistration);
r.get('/jobs', c.getJobs);
r.put('/jobs/:id', c.updateJob);
r.get('/stories', c.getStories);
r.delete('/stories/:id', c.deleteStory);
r.get('/users', c.getUsers);
r.delete('/users/:id', c.deleteUser);
r.get('/activity', c.getActivity);
module.exports = r;
